/* ArtHub COS runtime bridge. Generated by scripts/build-cos-web.cjs. */
(() => {
  'use strict';
  const cfg = window.ARTHUB_COS_CONFIG || {};
  const root = String(cfg.root || '').replace(/\/+$/, '');
  if (!root) return;

  const ASSET_MARKERS = [
    '/bd2/spine/', '/nikki/spine/',
    '/majsoul/assets_raw/', '/majsoul/web_illustrations/',
    '/gallery/bd2/', '/gallery/nikke/', '/gallery/majsoul/',
  ];

  function markerPath(pathname) {
    for (const marker of ASSET_MARKERS) {
      const at = pathname.indexOf(marker);
      if (at >= 0) return pathname.slice(at);
    }
    return null;
  }

  function resolve(input) {
    const source = input instanceof Request ? input.url : String(input);
    const url = new URL(source, location.href);
    if (url.origin !== location.origin) return url.href;
    const remotePath = markerPath(url.pathname);
    if (!remotePath) return url.href;
    return root + remotePath + url.search + url.hash;
  }

  window.ARTHUB_COS_ROOT = root;
  window.ARTHUB_COS_RESOLVE = resolve;
  const nativeFetch = window.fetch.bind(window);
  window.fetch = (input, init) => {
    let target;
    try { target = resolve(input); } catch { return nativeFetch(input, init); }
    const request = input instanceof Request ? new Request(target, input) : target;
    return nativeFetch(request, init);
  };

  // Spine's WebGL runtime uses XMLHttpRequest for atlas and texture files.
  // Rewrite those requests too; changing fetch alone leaves the viewer's
  // index working while every model reports a 404 from the static host.
  if (window.XMLHttpRequest && window.XMLHttpRequest.prototype && !window.XMLHttpRequest.prototype.__arthubCosPatched) {
    const nativeOpen = window.XMLHttpRequest.prototype.open;
    window.XMLHttpRequest.prototype.open = function(method, url, ...rest) {
      let target = url;
      try { target = resolve(url); } catch {}
      return nativeOpen.call(this, method, target, ...rest);
    };
    window.XMLHttpRequest.prototype.__arthubCosPatched = true;
  }

  // gallery_meta.json remains on the web site with the small indexes. Rewrite
  // only its mount URLs so the existing gallery page can stay unchanged.
  const fetchWithRewrite = window.fetch;
  window.fetch = (input, init) => fetchWithRewrite(input, init).then(async response => {
    let url = '';
    try { url = new URL(input instanceof Request ? input.url : String(input), location.href).pathname; } catch {}
    if (!/\/gallery\/(?:index\/)?gallery_meta\.json$/i.test(url) || !response.ok) return response;
    try {
      const data = await response.clone().json();
      for (const lib of data.libraries || []) {
        if (!lib || typeof lib.mount !== 'string' || !lib.mount.startsWith('/gallery/')) continue;
        lib.mount = root + lib.mount;
      }
      const headers = new Headers(response.headers);
      headers.delete('content-length');
      headers.delete('content-encoding');
      headers.set('content-type', 'application/json; charset=utf-8');
      return new Response(JSON.stringify(data), { status: response.status, statusText: response.statusText, headers });
    } catch { return response; }
  });
})();

