/* ArtHub COS runtime bridge. Generated by scripts/build-cos-web.cjs. */
(() => {
  'use strict';
  const cfg = window.ARTHUB_COS_CONFIG || {};
  const root = String(cfg.root || '').replace(/\/+$/, '');
  if (!root) return;

  const ASSET_MARKERS = [
    '/bd2/spine/', '/nikki/spine/', '/nikki/spine_carved/',
  ];

  const PATH_REWRITES = {
    // 页面索引沿用本地的 spine/ 相对路径；COS 里已上传的妮姬目录名是 spine_carved。
    '/nikki/spine/': '/nikki/spine_carved/',
  };

  function markerPath(pathname) {
    for (const [marker, remote] of Object.entries(PATH_REWRITES)) {
      const at = pathname.indexOf(marker);
      if (at >= 0) return remote + pathname.slice(at + marker.length);
    }
    for (const marker of ASSET_MARKERS) {
      const at = pathname.indexOf(marker);
      if (at >= 0) return pathname.slice(at);
    }
    return null;
  }

  function resolve(input) {
    const source = input instanceof Request ? input.url : String(input);
    const url = new URL(source, location.href);
    if (url.origin !== location.origin) return url.href;
    const remotePath = markerPath(url.pathname);
    if (!remotePath) return url.href;
    return root + remotePath + url.search + url.hash;
  }

  window.ARTHUB_COS_ROOT = root;
  window.ARTHUB_COS_RESOLVE = resolve;
  const nativeFetch = window.fetch.bind(window);
  window.fetch = (input, init) => {
    let target;
    try { target = resolve(input); } catch { return nativeFetch(input, init); }
    const request = input instanceof Request ? new Request(target, input) : target;
    return nativeFetch(request, init);
  };

  // Spine's WebGL runtime uses XMLHttpRequest for atlas and texture files.
  // Rewrite those requests too; changing fetch alone leaves the viewer's
  // index working while every model reports a 404 from the static host.
  if (window.XMLHttpRequest && window.XMLHttpRequest.prototype && !window.XMLHttpRequest.prototype.__arthubCosPatched) {
    const nativeOpen = window.XMLHttpRequest.prototype.open;
    window.XMLHttpRequest.prototype.open = function(method, url, ...rest) {
      let target = url;
      try { target = resolve(url); } catch {}
      return nativeOpen.call(this, method, target, ...rest);
    };
    window.XMLHttpRequest.prototype.__arthubCosPatched = true;
  }

  // Spine's browser loader creates HTMLImageElement instances and assigns
  // image.src directly for atlas page PNGs.  fetch/XHR interception does not
  // see that navigation, so rewrite the native src setter as well.
  if (window.HTMLImageElement && window.HTMLImageElement.prototype && !window.HTMLImageElement.prototype.__arthubCosPatched) {
    const descriptor = Object.getOwnPropertyDescriptor(window.HTMLImageElement.prototype, 'src');
    if (descriptor && typeof descriptor.set === 'function') {
      const nativeSet = descriptor.set;
      const patchedSet = function(value) {
        let target = value;
        if (value !== null && value !== undefined) {
          try { target = resolve(value); } catch {}
        }
        return nativeSet.call(this, target);
      };
      Object.defineProperty(window.HTMLImageElement.prototype, 'src', { ...descriptor, set: patchedSet });
      window.HTMLImageElement.prototype.__arthubCosPatched = true;
    }
  }

})();

